# Production Monitoring Stack for Crowd Due Dill
# Grafana + Prometheus with integrated email alerts
# Uses nginx-proxy for SSL and domain routing

services:
  # Prometheus - Metrics Collection and Storage
  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: crowd-due-dill-prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.retention.size=10GB'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.external-url=https://${DOMAIN_NAME}/prometheus/'
      - '--web.route-prefix=/prometheus/'
    environment:
      - VIRTUAL_HOST=${DOMAIN_NAME}
      - VIRTUAL_PATH=/prometheus/
      - VIRTUAL_PORT=9090
      - LETSENCRYPT_HOST=${DOMAIN_NAME}
      - LETSENCRYPT_EMAIL=${SSL_EMAIL}
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - monitoring
      - proxy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/prometheus/-/healthy"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Grafana - Dashboards and Alerting
  grafana:
    image: grafana/grafana:11.3.0
    container_name: crowd-due-dill-grafana
    restart: unless-stopped
    environment:
      # Domain and SSL configuration - PATH-BASED ROUTING
      - VIRTUAL_HOST=${DOMAIN_NAME}
      - VIRTUAL_PATH=/monitoring/
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=${DOMAIN_NAME}
      - LETSENCRYPT_EMAIL=${SSL_EMAIL}
      
      # Grafana configuration for path-based deployment
      - GF_SERVER_ROOT_URL=https://${DOMAIN_NAME}/monitoring/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_DOMAIN=${DOMAIN_NAME}
      - GF_SERVER_ENFORCE_DOMAIN=true
      
      # Security settings
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SECURITY_SECRET_KEY=${GRAFANA_SECRET_KEY}
      - GF_SECURITY_COOKIE_SECURE=true
      - GF_SECURITY_COOKIE_SAMESITE=strict
      
      # Email configuration for alerts
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=${SMTP_HOST}
      - GF_SMTP_PORT=${SMTP_PORT:-587}
      - GF_SMTP_USER=${SMTP_USER}
      - GF_SMTP_PASSWORD=${SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
      - GF_SMTP_FROM_NAME="Crowd Due Dill Monitoring"
      - GF_SMTP_SKIP_VERIFY=${SMTP_SKIP_VERIFY:-false}
      
      # Authentication and users
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Viewer
      
      # Database (use PostgreSQL for production)
      - GF_DATABASE_TYPE=sqlite3
      - GF_DATABASE_PATH=/var/lib/grafana/grafana.db
      
      # Logging
      - GF_LOG_MODE=console,file
      - GF_LOG_LEVEL=info
      
      # Enable alerting
      - GF_ALERTING_ENABLED=true
      - GF_UNIFIED_ALERTING_ENABLED=true
      
      # Disable analytics
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      
      # Feature toggles
      - GF_FEATURE_TOGGLES_ENABLE=alertingPreview
      
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring
      - proxy
    depends_on:
      - prometheus
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Node Exporter - System Metrics
  node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: crowd-due-dill-node-exporter
    restart: unless-stopped
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - monitoring
    ports:
      - "9100:9100"

  # cAdvisor - Container Metrics
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    container_name: crowd-due-dill-cadvisor
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitoring
    ports:
      - "8080:8080"

# Volumes for persistent data
volumes:
  prometheus_data:
    name: crowd_due_dill_prometheus_data
  grafana_data:
    name: crowd_due_dill_grafana_data

# Networks
networks:
  monitoring:
    name: crowd_due_dill_monitoring
    external: true
  proxy:
    name: proxy
    external: true 