modules:
  http_2xx:
    prober: http
    timeout: 10s
    http:
      method: GET
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200]
      follow_redirects: true
      preferred_ip_protocol: "ip4"
      headers:
        User-Agent: "Blackbox Exporter/Prometheus Health Check"
      fail_if_ssl: false
      fail_if_not_ssl: false
      
  http_post_2xx:
    prober: http
    timeout: 10s
    http:
      method: POST
      headers:
        Content-Type: application/json
      body: '{}'
      valid_status_codes: [200, 201]
      
  tcp_connect:
    prober: tcp
    timeout: 10s
    
  icmp:
    prober: icmp
    timeout: 10s
    icmp:
      preferred_ip_protocol: "ip4"
      
  dns:
    prober: dns
    timeout: 10s
    dns:
      query_name: "crowd-reg.beautiful-apps.com"
      query_type: "A"