apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090/prometheus
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
      queryTimeout: 60s
      # Enable exemplars for better debugging
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
      # Custom headers for production
      customQueryParameters: 
        step: '15s'
    secureJsonData: {}
    version: 1 