apiVersion: 1

groups:
  - name: crowd-due-dill-critical
    orgId: 1
    folder: alerts
    interval: 1m
    rules:
      - uid: app-down-alert
        title: Application Down
        condition: C
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: up{job="crowd-due-dill-api"} == 0
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: C
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [0]
                    type: lt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    params: []
                    type: last
                  type: query
              datasourceUid: __expr__
              expression: A
              refId: C
        noDataState: Alerting
        execErrState: Alerting
        for: 1m
        annotations:
          summary: "Crowd Due Dill application is down"
          description: "The main application has been unreachable for more than 1 minute"
        labels:
          severity: critical
          service: api
          team: devops

      - uid: high-error-rate-alert
        title: High Error Rate
        condition: C
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: rate(http_requests_total{job="crowd-due-dill-api",status=~"5.."}[5m]) / rate(http_requests_total{job="crowd-due-dill-api"}[5m]) * 100
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: C
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [10]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    params: []
                    type: last
                  type: query
              datasourceUid: __expr__
              expression: A
              refId: C
        noDataState: NoData
        execErrState: Alerting
        for: 2m
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 10% for the last 2 minutes"
        labels:
          severity: critical
          service: api
          team: devops

      - uid: high-memory-usage-alert
        title: High Memory Usage
        condition: C
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: C
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [90]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    params: []
                    type: last
                  type: query
              datasourceUid: __expr__
              expression: A
              refId: C
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          summary: "High memory usage on server"
          description: "Memory usage is above 90% for the last 5 minutes"
        labels:
          severity: critical
          service: system
          team: devops

  - name: crowd-due-dill-warnings
    orgId: 1
    folder: alerts
    interval: 2m
    rules:
      - uid: slow-response-alert
        title: Slow Response Times
        condition: C
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="crowd-due-dill-api"}[5m]))
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: C
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [5]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    params: []
                    type: last
                  type: query
              datasourceUid: __expr__
              expression: A
              refId: C
        noDataState: NoData
        execErrState: Alerting
        for: 3m
        annotations:
          summary: "Application response times are slow"
          description: "95th percentile response time is above 5 seconds"
        labels:
          severity: warning
          service: api
          team: devops

      - uid: high-cpu-usage-alert
        title: High CPU Usage
        condition: C
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: C
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [80]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    params: []
                    type: last
                  type: query
              datasourceUid: __expr__
              expression: A
              refId: C
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for the last 5 minutes"
        labels:
          severity: warning
          service: system
          team: devops

      - uid: disk-space-low-alert
        title: Low Disk Space
        condition: C
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: (node_filesystem_size_bytes{fstype!="tmpfs"} - node_filesystem_free_bytes{fstype!="tmpfs"}) / node_filesystem_size_bytes{fstype!="tmpfs"} * 100
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: C
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [85]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    params: []
                    type: last
                  type: query
              datasourceUid: __expr__
              expression: A
              refId: C
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          summary: "Low disk space warning"
          description: "Disk usage is above 85%"
        labels:
          severity: warning
          service: system
          team: devops 