apiVersion: 1

# Notification policies
policies:
  - orgId: 1
    receiver: default-email
    group_by: ['alertname', 'cluster', 'service']
    group_wait: 10s
    group_interval: 10s
    repeat_interval: 1h
    routes:
      - receiver: critical-email
        group_wait: 10s
        group_interval: 5m
        repeat_interval: 5m
        matchers:
          - severity = critical
        continue: false
      - receiver: warning-email
        group_wait: 30s
        group_interval: 10m
        repeat_interval: 30m
        matchers:
          - severity = warning
        continue: false

# Contact points (notification channels)
contactPoints:
  - orgId: 1
    name: default-email
    receivers:
      - uid: default-email-uid
        type: email
        settings:
          addresses: admin@crowd-reg.beautiful-apps.com
          subject: "[Crowd Due Dill] {{ .GroupLabels.alertname }}"
          message: |
            {{ range .Alerts }}
            **Alert**: {{ .Annotations.summary }}
            **Description**: {{ .Annotations.description }}
            **Severity**: {{ .Labels.severity }}
            **Service**: {{ .Labels.service }}
            **Time**: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
            {{ if .GeneratorURL }}**Link**: {{ .GeneratorURL }}{{ end }}
            {{ end }}
        disableResolveMessage: false

  - orgId: 1
    name: critical-email
    receivers:
      - uid: critical-email-uid
        type: email
        settings:
          addresses: admin@crowd-reg.beautiful-apps.com, team@crowd-reg.beautiful-apps.com
          subject: "🚨 CRITICAL: [Crowd Due Dill] {{ .GroupLabels.alertname }}"
          message: |
            **🚨 CRITICAL ALERT 🚨**
            
            {{ range .Alerts }}
            **Alert**: {{ .Annotations.summary }}
            **Description**: {{ .Annotations.description }}
            **Severity**: {{ .Labels.severity }}
            **Service**: {{ .Labels.service }}
            **Instance**: {{ .Labels.instance }}
            **Started**: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
            {{ if .GeneratorURL }}**Dashboard**: {{ .GeneratorURL }}{{ end }}
            
            **Immediate action required!**
            {{ end }}
        disableResolveMessage: false

  - orgId: 1
    name: warning-email
    receivers:
      - uid: warning-email-uid
        type: email
        settings:
          addresses: team@crowd-reg.beautiful-apps.com
          subject: "⚠️  WARNING: [Crowd Due Dill] {{ .GroupLabels.alertname }}"
          message: |
            **⚠️ Warning Alert**
            
            {{ range .Alerts }}
            **Alert**: {{ .Annotations.summary }}
            **Description**: {{ .Annotations.description }}
            **Service**: {{ .Labels.service }}
            **Started**: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
            {{ if .GeneratorURL }}**Dashboard**: {{ .GeneratorURL }}{{ end }}
            {{ end }}
        disableResolveMessage: false 